---
title: TI10KO
timezone: Europe/Warsaw
collections:
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Maksym Titenko
description: Околотехно блог
avatar: https://raw.githubusercontent.com/titenko/titenko.github.io/master/images/ti10ko.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: titenko
  instagram: 
  linkedin: 
  pinterest: 
  rss: feed.xml
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: https-titenko-github-io
google_analytics: 
url: https://titenko.github.io
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
- jekyll-redirect-from
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
