---
title: Titenko.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Maksym Titenko
description: Добро пожаловать в мой блог
avatar: https://raw.githubusercontent.com/titenko/titenko.github.io/master/images/jekyll-logo.jpg
footer-links:
  telegram: MaksymTitenko
  dribbble: 
  email: 
  facebook: titenko.maksym
  flickr: 
  github: titenko
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: titenko_maksym
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: https-titenko-github-io
google_analytics: 
url: https://titenko.github.io/
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
theme: jekyll-theme-slate
